### ISSUE TITLE
Error 404 connecting to the unifi

### ISSUE THREAD

**Issue by rickitaly** [mannkind/unifi2mqtt#22] opened 2021-04-07 19:46 UTC
Hello i configured a docker on unRAID, i run but got an error.
Here is my docker run:
`docker run -d --name='unifi2mqtt' --net='br0.30' --ip='192.168.xx.xx' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'UNIFI__HOST'='https://192.168.1.100:8443' -e 'UNIFI__USERNAME'='myuser' -e 'UNIFI__PASSWORD'='mypass' -e 'UNIFI__AWAYTIMEOUT'='0.00:05:01' -e 'UNIFI__RESOURCES__0__MACAddress'='mycellmac' -e 'UNIFI__RESOURCES__0__Slug'='mycellname' -e 'UNIFI__MQTT__BROKER'='mymqttbroker' -e 'UNIFI__MQTT__USERNAME'='mqttuser' -e 'UNIFI__MQTT__PASSWORD'='mqttpass' 'mannkind/unifi2mqtt'
`
I can access to the unifi at this address https://192.168.1.100:8443/ . I get the certificate error but i can skip.
If i try to browse to https://192.168.1.100:8443/proxy/network/api/s/default/stat/sta i get 404.
As i said the docker starts but here is the log. 
unifi is 6.1.71
 
`[21:42:14] info: Unifi.Liasons.SourceLiason[0]
Host: https://192.168.1.100:8443
Username: myuser
Password: <REDACTED>
Site: default
AwayTimeout: 00:05:01
PollingInterval: 00:00:11
Resources: SlugMapping { MACAddress = mycellmac, Slug = mycellname}

[21:42:14] info: TwoMQTT.Managers.MQTTManager[0]
Broker: 192.168.20.100
TopicPrefix: home/unifi
DiscoveryEnabled: True
DiscoveryPrefix: homeassistant
DiscoveryName: unifi

[21:42:14] info: TwoMQTT.Managers.SourceManager[0]
Awaiting incoming commands
[21:42:14] info: TwoMQTT.Managers.SourceManager[0]
Polling source
[21:42:14] info: System.Net.Http.HttpClient.ApiControllerDetection.LogicalHandler[100]
Start processing HTTP request GET https://192.168.1.100:8443/
[21:42:14] info: System.Net.Http.HttpClient.ApiControllerDetection.ClientHandler[100]
Sending HTTP request GET https://192.168.1.100:8443/
[21:42:14] info: TwoMQTT.Managers.MQTTManager[0]
Awaiting incoming data
[21:42:14] info: System.Net.Http.HttpClient.ApiControllerDetection.ClientHandler[101]
Received HTTP response headers after 170.7435ms - 200
[21:42:14] info: System.Net.Http.HttpClient.ApiControllerDetection.LogicalHandler[101]
End processing HTTP request after 178.5706ms - 200
[21:42:14] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
Start processing HTTP request POST https://192.168.1.100:8443/api/auth/login
[21:42:14] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
Sending HTTP request POST https://192.168.1.100:8443/api/auth/login
[21:42:14] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
Received HTTP response headers after 16.7927ms - 401
[21:42:14] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]
End processing HTTP request after 16.8701ms - 401
[21:42:14] info: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
[21:42:14] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
Start processing HTTP request GET https://192.168.1.100:8443/proxy/network/api/s/default/stat/sta
[21:42:14] info: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production
[21:42:14] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
Sending HTTP request GET https://192.168.1.100:8443/proxy/network/api/s/default/stat/sta
[21:42:14] info: Microsoft.Hosting.Lifetime[0]
Content root path: /app/
[21:42:14] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
Received HTTP response headers after 1.0177ms - 404
[21:42:14] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]
End processing HTTP request after 1.0596ms - 404
[21:42:14] fail: Unifi.DataAccess.SourceDAO[0]
Unable to deserialize response from the Unifi API; Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
at Newtonsoft.Json.JsonTextReader.ParseValue()
at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
at Unifi.DataAccess.Api.GetActiveClients(CancellationToken cancellation) in /home/runner/work/unifi2mqtt/unifi2mqtt/Unifi/DataAccess/Api.cs:line 46
at Unifi.DataAccess.SourceDAO.AllClientsAsync(CancellationToken cancellationToken) in /home/runner/work/unifi2mqtt/unifi2mqtt/Unifi/DataAccess/SourceDAO.cs:line 183
at Unifi.DataAccess.SourceDAO.FetchAsync(String macAddress, CancellationToken cancellationToken) in /home/runner/work/unifi2mqtt/unifi2mqtt/Unifi/DataAccess/SourceDAO.cs:line 132
at Unifi.DataAccess.SourceDAO.FetchOneAsync(SlugMapping data, CancellationToken cancellationToken) in /home/runner/work/unifi2mqtt/unifi2mqtt/Unifi/DataAccess/SourceDAO.cs:line 53
[21:42:25] info: System.Net.Http.HttpClient.ApiControllerDetection.LogicalHandler[100]
Start processing HTTP request GET https://192.168.1.100:8443/
[21:42:25] info: System.Net.Http.HttpClient.ApiControllerDetection.ClientHandler[100]
Sending HTTP request GET https://192.168.1.100:8443/
[21:42:25] info: System.Net.Http.HttpClient.ApiControllerDetection.ClientHandler[101]
Received HTTP response headers after 2.8043ms - 200
[21:42:25] info: System.Net.Http.HttpClient.ApiControllerDetection.LogicalHandler[101]
End processing HTTP request after 2.8895ms - 200
[21:42:25] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
Start processing HTTP request POST https://192.168.1.100:8443/api/auth/login
[21:42:25] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
Sending HTTP request POST https://192.168.1.100:8443/api/auth/login
[21:42:25] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
Received HTTP response headers after 0.7915ms - 401
[21:42:25] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]
End processing HTTP request after 0.8418ms - 401
[21:42:25] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
Start processing HTTP request GET https://192.168.1.100:8443/proxy/network/api/s/default/stat/sta
[21:42:25] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
Sending HTTP request GET https://192.168.1.100:8443/proxy/network/api/s/default/stat/sta
[21:42:25] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
Received HTTP response headers after 0.8018ms - 404
[21:42:25] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]
End processing HTTP request after 0.8556ms - 404
[21:42:25] fail: Unifi.DataAccess.SourceDAO[0]
Unable to deserialize response from the Unifi API; Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
at Newtonsoft.Json.JsonTextReader.ParseValue()
at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
at Unifi.DataAccess.Api.GetActiveClients(CancellationToken cancellation) in /home/runner/work/unifi2mqtt/unifi2mqtt/Unifi/DataAccess/Api.cs:line 46
at Unifi.DataAccess.SourceDAO.AllClientsAsync(CancellationToken cancellationToken) in /home/runner/work/unifi2mqtt/unifi2mqtt/Unifi/DataAccess/SourceDAO.cs:line 183
at Unifi.DataAccess.SourceDAO.FetchAsync(String macAddress, CancellationToken cancellationToken) in /home/runner/work/unifi2mqtt/unifi2mqtt/Unifi/DataAccess/SourceDAO.cs:line 132
at Unifi.DataAccess.SourceDAO.FetchOneAsync(SlugMapping data, CancellationToken cancellationToken) in /home/runner/work/unifi2mqtt/unifi2mqtt/Unifi/DataAccess/SourceDAO.cs:line 53`

Any help?

**Comment by rickitaly** [comment] 2021-04-08 06:44
Having a look at the source code, it seems that this.UniFiOS flag is changing the path, while it should not because i don't have a UniFiOS (controller it's running on docker)
I saw in many other apps that UniFiOS option is a flag you can set as external parameter, could it be the case also for this?

**Comment by mannkind** [comment] 2021-04-27 03:38
Sorry I missed this, I didn't get notified for some reason.

At the moment I'd rather not make the UniFiOS flag configurable, the current method _should_ detect it based on the behavior of the controller -- the standalone controller 302 redirects; the UniFiOS controller responds with 200.

Actually, I think I might see the problem. If I recall correctly the controller detection http client **cannot** follow redirects, and it looks like I hard-coded allowing redirects when cleaning up the coed.

Let me see if I can't fix test that assumption and fix it.

**Comment by mannkind** [comment] 2021-04-27 04:08
@rickitaly  should you still be interested/have a moment, the `latest` tag should have a fix in place.

I was able to start a docker container with the controller and reproduce the issue with the wrong URLs due to incorrectly thinking it was running on UniFiOS. Fixing the follow redirect flag _appears_ to have solved the issue ( although I don't have a good way of testing clients to a isolated controller ) and it's still working against my CloudKey Plus.

```
[03:54:07] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
      Start processing HTTP request GET https://10.0.100.100:8443/api/s/default/stat/sta
[03:54:07] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
      Sending HTTP request GET https://10.0.100.100:8443/api/s/default/stat/sta
[03:54:07] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
      Received HTTP response headers after 7.9769ms - 200
[03:54:07] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]
      End processing HTTP request after 8.1655ms - 200
[03:54:07] dbug: Unifi.DataAccess.SourceDAO[0]
      Caching 0 clients
```

**Comment by rickitaly** [comment] 2021-04-27 06:40
> @rickitaly should you still be interested/have a moment, the `latest` tag should have a fix in place.
> 
> I was able to start a docker container with the controller and reproduce the issue with the wrong URLs due to incorrectly thinking it was running on UniFiOS. Fixing the follow redirect flag _appears_ to have solved the issue ( although I don't have a good way of testing clients to a isolated controller ) and it's still working against my CloudKey Plus.
> 
> ```
> [03:54:07] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
>       Start processing HTTP request GET https://10.0.100.100:8443/api/s/default/stat/sta
> [03:54:07] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
>       Sending HTTP request GET https://10.0.100.100:8443/api/s/default/stat/sta
> [03:54:07] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
>       Received HTTP response headers after 7.9769ms - 200
> [03:54:07] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]
>       End processing HTTP request after 8.1655ms - 200
> [03:54:07] dbug: Unifi.DataAccess.SourceDAO[0]
>       Caching 0 clients
> ```

Hello, thanks for your support!
I updated the docker and indeed that error disappeared! Great!
Now the problem is that everything seems OK but i can't see anything published to the MQTT broker.
Here is the log:
`[08:34:58] info: Unifi.Liasons.SourceLiason[0]
Host: -UNIFIHOSTADDR-
Username: rickitaly
Password: -REDACTED-
Site: default
AwayTimeout: 00:05:01
PollingInterval: 00:00:11
Resources: SlugMapping { MACAddress = -CELLMACADDR-, Slug = P30Pro }

[08:34:58] info: TwoMQTT.Managers.MQTTManager[0]
Broker: -MQTTBROKERADDR-
TopicPrefix: home/unifi
DiscoveryEnabled: True
DiscoveryPrefix: homeassistant
DiscoveryName: unifi

[08:34:58] info: TwoMQTT.Managers.SourceManager[0]
Awaiting incoming commands
[08:34:58] info: TwoMQTT.Managers.SourceManager[0]
Polling source
[08:34:58] info: System.Net.Http.HttpClient.ApiControllerDetection.LogicalHandler[100]
Start processing HTTP request GET https://-UNIFIHOSTADDR-/
[08:34:58] info: System.Net.Http.HttpClient.ApiControllerDetection.ClientHandler[100]
Sending HTTP request GET https://-UNIFIHOSTADDR-/
[08:34:58] info: TwoMQTT.Managers.MQTTManager[0]
Awaiting incoming data
[08:34:58] info: System.Net.Http.HttpClient.ApiControllerDetection.ClientHandler[101]
Received HTTP response headers after 170.6156ms - 302
[08:34:58] info: System.Net.Http.HttpClient.ApiControllerDetection.LogicalHandler[101]
End processing HTTP request after 178.4167ms - 302
[08:34:58] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
Start processing HTTP request POST https://-UNIFIHOSTADDR-/api/login
[08:34:58] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
Sending HTTP request POST https://-UNIFIHOSTADDR-/api/login
[08:34:58] info: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
[08:34:58] info: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production
[08:34:58] info: Microsoft.Hosting.Lifetime[0]
Content root path: /app/
[08:34:59] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
Received HTTP response headers after 912.723ms - 200
[08:34:59] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]
End processing HTTP request after 912.8248ms - 200
[08:34:59] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
Start processing HTTP request GET https://-UNIFIHOSTADDR-/api/s/default/stat/sta
[08:34:59] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
Sending HTTP request GET https://-UNIFIHOSTADDR-/api/s/default/stat/sta
[08:34:59] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
Received HTTP response headers after 3.0233ms - 200
[08:34:59] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]
End processing HTTP request after 3.0745ms - 200
[08:34:59] info: TwoMQTT.Managers.MQTTManager[0]
Publishing 'ON' on 'home/unifi/p30pro/state'
[08:35:10] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
Start processing HTTP request GET https://-UNIFIHOSTADDR-/api/s/default/stat/sta
[08:35:10] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
Sending HTTP request GET https://-UNIFIHOSTADDR-/api/s/default/stat/sta
[08:35:10] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
Received HTTP response headers after 2.183ms - 200
[08:35:10] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]
End processing HTTP request after 2.321ms - 200
[08:35:21] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
Start processing HTTP request GET https://-UNIFIHOSTADDR-/api/s/default/stat/sta
[08:35:21] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
Sending HTTP request GET https://-UNIFIHOSTADDR-/api/s/default/stat/sta
[08:35:21] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
Received HTTP response headers after 2.0169ms - 200
[08:35:21] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]
End processing HTTP request after 2.1587ms - 200
[08:35:32] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
Start processing HTTP request GET https://-UNIFIHOSTADDR-/api/s/default/stat/sta
[08:35:32] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
Sending HTTP request GET https://-UNIFIHOSTADDR-/api/s/default/stat/sta
[08:35:32] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
Received HTTP response headers after 1.9235ms - 200
[08:35:32] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]
End processing HTTP request after 2.0452ms - 200
[08:35:43] info: System.Net.Http.HttpClient.Api.LogicalHandler[100]
Start processing HTTP request GET https://-UNIFIHOSTADDR-/api/s/default/stat/sta
[08:35:43] info: System.Net.Http.HttpClient.Api.ClientHandler[100]
Sending HTTP request GET https://-UNIFIHOSTADDR-/api/s/default/stat/sta
[08:35:43] info: System.Net.Http.HttpClient.Api.ClientHandler[101]
Received HTTP response headers after 1.6447ms - 200
[08:35:43] info: System.Net.Http.HttpClient.Api.LogicalHandler[101]`

**Comment by mannkind** [comment] 2021-04-28 01:29
Woot. At least we're making progress.

It is trying to publish to MQTT: `Publishing 'ON' on 'home/unifi/p30pro/state'`
The MQTT lib I'm using won't die when it can't connect to the broker; it'll just auto-retry and  queue the commands in the mean time. 

Based on your earlier Docker command, I think it's related to the MQTT username/password. Specifically it looks like I never actually implemented adding credentials **(ugh)**. 

I should be able to work on that later this evening.

**Comment by rickitaly** [comment] 2021-04-28 05:46
> Woot. At least we're making progress.
> 
> It is trying to publish to MQTT: `Publishing 'ON' on 'home/unifi/p30pro/state'`
> The MQTT lib I'm using won't die when it can't connect to the broker; it'll just auto-retry and queue the commands in the mean time.
> 
> Based on your earlier Docker command, I think it's related to the MQTT username/password. Specifically it looks like I never actually implemented adding credentials **(ugh)**.
> 
> I should be able to work on that later this evening.

Hello! Yes indeed my broker needs credentials to login, and i couldn't find anything related in the log so i supposed it was ok...
Also other thing i noticed is that ok there is the "ON" publishing but after i disconnect the device from the network there is no OFF publishing (even after the delay).
Thanks!

**Comment by mannkind** [comment] 2021-04-28 06:26
The ability to use use a username/password with the mqtt broker should be coming soon. I'm testing the base twomqtt library this app uses now.

A note about publishing 'OFF': I promise it does publish 'OFF' -- I rely on the functionality, although I don't use the standalone controller anymore -- but the timing is a bit more complicated than _just_ the away timeout. The controller reports the device as connected for quite awhile after it disconnects (something like 3-5 mins, IIRC) so there is a bit of play in the total time before a device is marked as away. 

The app used to use the API's reported property "last_seen", but I found it to be even more inaccurate than just relying on the controller to stop reporting the client as connected. Mayyybe Ubiquiti has fixed that glitch; I haven't checked in quite awhile now.

**Comment by rickitaly** [comment] 2021-04-28 06:29
> The ability to use use a username/password with the mqtt broker should be coming soon. I'm testing the base twomqtt library this app uses now.
> 
> A note about publishing 'OFF': I promise it does publish 'OFF' -- I rely on the functionality, although I don't use the standalone controller anymore -- but the timing is a bit more complicated than _just_ the away timeout. The controller reports the device as connected for quite awhile after it disconnects (something like 3-5 mins, IIRC) so there is a bit of play in the total time before a device is marked as away.
> 
> The app used to use the API's reported property "last_seen", but I found it to be even more inaccurate than just relying on the controller to stop reporting the client as connected. Mayyybe Ubiquiti has fixed that glitch; I haven't checked in quite awhile now.

What i noticed is that the device already disappeared from the JSON, but i didnt get any log for OFF message published

**Comment by mannkind** [comment] 2021-04-28 06:40
Correct. Once the controller stops reporting the client is when the away timeout becomes a factor.
Personally I found that occasionally my phone wouldn't be reported as connected by the controller (despite it being on the wifi from what I could tell); in short that's why it's still `controller stops reporting + away timeout`.

**Comment by mannkind** [comment] 2021-04-29 00:43
Github actions reran the workflow and uploaded new docker images. You should now see Username/Password fields in the `TwoMQTT.Managers.MQTTManager` logging output to let you know A) You have the newest docker image, and B) You've set the env variables correctly.

Example:
```
[17:36:14] info: TwoMQTT.Managers.MQTTManager[0]
      Broker:            localhost
      Username:          testUser
      Password:          <REDACTED>
      TopicPrefix:       home/unifi
      DiscoveryEnabled:  True
      DiscoveryPrefix:   homeassistant
      DiscoveryName:     unifi
```

**Comment by rickitaly** [comment] 2021-04-29 06:19
> Github actions reran the workflow and uploaded new docker images. You should now see Username/Password fields in the `TwoMQTT.Managers.MQTTManager` logging output to let you know A) You have the newest docker image, and B) You've set the env variables correctly.
> 
> Example:
> 
> ```
> [17:36:14] info: TwoMQTT.Managers.MQTTManager[0]
>       Broker:            localhost
>       Username:          testUser
>       Password:          <REDACTED>
>       TopicPrefix:       home/unifi
>       DiscoveryEnabled:  True
>       DiscoveryPrefix:   homeassistant
>       DiscoveryName:     unifi
> ```

Hello! I am able now to get the status published to mqtt, also with credentials!
Thanks
I tried then to add another device to be identified and thats also ok!
I think i am more than satisfied now to use this docker together with my openHAB!
If you want some idea, could be interesting to publish to mqtt a more complete payload, even the whole unifi api published JSON for the device could be useful to get some more insights ;-)
 Thanks again

**Comment by rickitaly** [comment] 2021-04-29 06:26
Maybe one point to improve could be that every time you discover again the device (like 10 seconds) you publish again the status to MQTT; this could be useful if i restart my clients. Also i have a channel that tells me what is the latest update for an item, and this would confirm me that the detection is running...
What do you think about this?
Thanks again

**Comment by mannkind** [comment] 2021-04-29 06:54
Glad it's finally functioning! Check off one bug, and one _feature_. Heh. 
 
RE: Publishing the entire UniFi payload, probably not going to happen. I'm concerned about presence detection with this project. If you want data out of the controller, might I suggest something like [unifi poller](https://github.com/unifi-poller/unifi-poller)? I've used it in the past; it's quite neat. 

RE: publishing duplicate/known payloads. I'll take the suggestion under consideration. The change would impact all my "2mqtt" apps as deduplcating known payloads happens outside the app implementation code.

**Closed as completed** 2021-04-29 06:54 UTC
